server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/auth/ {
        proxy_pass http://auth-service:3001/api/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/applications {
        proxy_pass http://jobapp-service:3002/api/applications;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 10m;
    }

    location /uploads/ {
        proxy_pass http://jobapp-service:3002/uploads/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
