sonar.projectKey=job-app-ci
sonar.projectName=Job Application Platform
sonar.projectVersion=1.0

sonar.modules=auth-service,jobapp-service
auth-service.sonar.projectBaseDir=auth-service
jobapp-service.sonar.projectBaseDir=jobapp-service

sonar.qualitygate.wait=true
